[build]
  command = "bun run build && mkdir -p dist && cp -r .next/* dist/ 2>/dev/null || true"
  publish = "dist"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
