[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "latest"

# Optimized serverless functions configuration
[functions]
  node_bundler = "esbuild"
  # Optimize function size and performance
  timeout = 30
  # Only include essential runtime dependencies, not dev dependencies
  included_files = [
    ".next/server/**",
    ".next/static/**",
    ".env*"
  ]
  # Exclude large development and build dependencies
  external_node_modules = [
    "@next/swc-*",
    "@biomejs/biome",
    "eslint*",
    "typescript",
    "turbopack*",
    "webpack*",
    "@types/*",
    "postcss",
    "tailwindcss",
    "workbox-webpack-plugin",
    "critters"
  ]

# Alternative: Static deployment if function is still too large
# Uncomment these lines if serverless deployment continues to fail
# [build]
#   command = "npm ci && npm run build && npm run export"
#   publish = "out"

[dev]
  command = "npm run dev"
  port = 3000
