const blogPosts = [
  {
    id: 1,
    title: "The Future of SME Growth: How AI is Revolutionising Marketing in 2024",
    slug: "ai-marketing-automation",
    excerpt: "Discover how small and medium enterprises are leveraging artificial intelligence to compete with industry giants and achieve unprecedented growth rates.",
    category: "AI & Marketing",
    author: "Martin",
    date: "2024-06-01",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop",
    featured: true,
  },
  {
    id: 2,
    title: "Creating Seamless B2B User Experiences That Convert",
    slug: "seamless-b2b-user-experiences",
    excerpt: "Discover how to create B2B user experiences that guide real people toward confident decisions and drive meaningful conversions.",
    category: "User Experience",
    author: "Martin",
    date: "2024-06-15",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 3,
    title: "Mastering Thought Leadership Content on LinkedIn",
    slug: "thought-leadership-content-linkedin",
    excerpt: "Learn how to create authentic thought leadership content that builds trust, drives engagement, and generates real business results on LinkedIn.",
    category: "Content Strategy",
    author: "Martin",
    date: "2024-06-10",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 4,
    title: "The Complete Guide to SEO Topic Clusters and Content Mapping",
    slug: "seo-topic-clusters-content-mapping",
    excerpt: "Learn how to organize your content into strategic topic clusters that build topical authority and drive higher search rankings.",
    category: "SEO",
    author: "Martin",
    date: "2024-06-05",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 5,
    title: "Content Calendar Systems That Actually Work",
    slug: "content-calendar-systems",
    excerpt: "Discover how to build content calendars that drive consistent results through strategic planning and systematic execution.",
    category: "Content Strategy",
    author: "Martin",
    date: "2024-05-28",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 6,
    title: "Google Marketing Live 2025: The AI Search Revolution",
    slug: "google-marketing-live-2025",
    excerpt: "Discover the massive implications of Google Marketing Live 2025 and learn how to prepare your marketing strategy for the AI-first future.",
    category: "AI & Marketing",
    author: "Martin",
    date: "2024-05-25",
    readTime: "9 min read",
    image: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 7,
    title: "Mastering GA4's Cross-Network Channel Attribution",
    slug: "ga4-cross-network-attribution",
    excerpt: "Learn how to understand and optimize GA4's Cross-Network channel for better attribution and campaign performance insights.",
    category: "Analytics",
    author: "Martin",
    date: "2024-05-22",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 8,
    title: "Planning B2B Marketing Campaigns That Actually Work",
    slug: "b2b-marketing-campaigns",
    excerpt: "Discover how to plan B2B marketing campaigns that balance immediate conversions with long-term brand building for sustainable growth.",
    category: "Campaign Strategy",
    author: "Martin",
    date: "2024-05-18",
    readTime: "9 min read",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 9,
    title: "Navigating AI-Powered Search: Beyond Traditional SEO",
    slug: "ai-powered-search-beyond-seo",
    excerpt: "Learn how to adapt your search strategy for the AI era by embracing total search optimization across all discovery channels.",
    category: "SEO",
    author: "Martin",
    date: "2024-05-15",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 10,
    title: "Data-Driven Storytelling: Cutting Through Content Noise",
    slug: "data-driven-storytelling",
    excerpt: "Learn how to create breakthrough content by combining data insights with authentic storytelling that cuts through AI-generated noise.",
    category: "Content Strategy",
    author: "Martin",
    date: "2024-05-30",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 11,
    title: "Server-Side Tracking: Solving Modern Data Collection Challenges",
    slug: "server-side-tracking",
    excerpt: "Discover how server-side tracking can improve your data accuracy by 20-30% while maintaining compliance with privacy regulations.",
    category: "Marketing Technology",
    author: "Martin",
    date: "2024-05-12",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 12,
    title: "Conversion APIs: The Future of Campaign Performance",
    slug: "conversion-apis-future",
    excerpt: "Learn how Conversion APIs can improve your campaign performance by 20-30% while future-proofing your tracking in the post-cookie era.",
    category: "Marketing Technology",
    author: "Martin",
    date: "2024-05-08",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop",
    featured: false,
  },
  {
    id: 13,
    title: "Zero-Click Search: The New SEO Reality",
    slug: "zero-click-search-reality",
    excerpt: "Learn how to adapt your SEO strategy for the zero-click search era by focusing on visibility, authority, and brand building over traffic generation.",
    category: "SEO",
    author: "Martin",
    date: "2024-05-05",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&h=300&fit=crop",
    featured: false,
  },
];
